data:
  seed: 42 
  sample_rate: 8000
  samples:
    clean: ${hydra:runtime.cwd}/data_small/clean
    noisy: ${hydra:runtime.cwd}/data_small/noisy
  cache: cache

stft:
  n_fft: 256
  hop_length: 64
  win_length: 256
  input_frames: 8
  output_frames: 1
  max_phase_diff: 45

model:
  filters: [10, 12, 14, 15, 19, 21, 23, 25, 23, 21, 19, 15, 14, 12, 10]
  kernels: [11,  7,  5,  5,  5,  5,  7, 11,  7,  5,  5,  5,  5,  7, 11]
  activation: "relu"

train:
  epochs: 50
  batch_size: 64
  lr_scheduler:
    patience: 4
    factor: 0.5
    min_lr: 1e-6
  optimizer:
    lr: 0.0015
    betas: [0.9, 0.999]
    eps: 1e-8

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
  